version: '3.8'

services:
  randomrobi-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: randomrobi_db
      MYSQL_USER: randomrobi_user
      MYSQL_PASSWORD: securepassword123
      MYSQL_ROOT_PASSWORD: rootsecurepassword456
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/my.cnf:/etc/mysql/my.cnf
    networks:
      - randomrobi-network
    command: --default-authentication-plugin=mysql_native_password

  randomrobi-backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: randomrobi-db
      DB_PORT: 3306
      DB_NAME: randomrobi_db
      DB_USER: randomrobi_user
      DB_PASSWORD: securepassword123
      JWT_SECRET: your-super-secure-jwt-secret-key-minimum-32-characters-long-for-production
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@randomrobi.com
      ADMIN_PASSWORD: AdminPass123!
      CORS_ORIGIN: http://localhost:4200,http://localhost:80
      CREATE_TABLES: true
      BCRYPT_ROUNDS: 12
    depends_on:
      - randomrobi-db
    networks:
      - randomrobi-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  randomrobi-frontend:
    build:
      context: ./frontend
    ports:
      - '4200:80'
    networks:
      - randomrobi-network
    depends_on:
      - randomrobi-backend
    restart: unless-stopped

networks:
  randomrobi-network:

volumes:
  db_data:
