version: '3.8'

services:
  randomrobi-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - randomrobi-network
    ports:
      - "3306:3306"

  randomrobi-backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: randomrobi-db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - randomrobi-db
    networks:
      - randomrobi-network

  randomrobi-frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - randomrobi-network

networks:
  randomrobi-network:

volumes:
  db_data: