version: '3.8'

services:
  randomrobi-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: randomrobi_db
      MYSQL_USER: randomrobi_user
      MYSQL_PASSWORD: securepassword123
      MYSQL_ROOT_PASSWORD: rootsecurepassword456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - randomrobi-network
    ports:
      - '3306:3306'

  randomrobi-backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      DB_HOST: randomrobi-db
      DB_PORT: 3306
      DB_NAME: randomrobi_db
      DB_USER: randomrobi_user
      DB_PASSWORD: securepassword123
    depends_on:
      - randomrobi-db
    networks:
      - randomrobi-network

  randomrobi-frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    networks:
      - randomrobi-network

networks:
  randomrobi-network:

volumes:
  db_data:
